name: devel-rerender-all-packages

on:
  workflow_dispatch:
  # call every sunday at 10am
  # schedule:
  #   - cron: 0 10 * * 0

jobs:
  rerender-sofa:
    uses: ./.github/workflows/rerender-package.yml
    with:
      package: sofa
      release: devel
      requires-prs: ""
    secrets: inherit
  rerender-sofa-python3:
    needs: rerender-sofa
    uses: ./.github/workflows/rerender-package.yml
    with:
      package: sofa-python3
      release: devel
      requires-prs: ${{ needs.rerender-sofa.outputs.pr-number }}
    secrets: inherit
