name: sofa-cosserat
on:
  - workflow_call
  - workflow_dispatch

jobs:
  build-publish-sofa-cosserat:
    strategy:
      fail-fast: false
      matrix:
        target: [{platform: "linux-64", runner: "ubuntu-latest"},
                  {platform: "linux-aarch64", runner: "ubuntu-22.04-arm"},
                  {platform: "osx-64", runner: "macos-13"},
                  {platform: "osx-arm64", runner: "macos-14"},
                  {platform: "win-64", runner: "windows-latest"}]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    uses: ./.github/workflows/build_publish_package.yml
    with:
      package-name: sofa-cosserat
      runner: ${{ matrix.target.runner }}
      platform: ${{ matrix.target.platform }}
      python: ${{ matrix.python }}
      anaconda-channel: sofa-framework
      recipe-dir: release-v25.06
    secrets:
      anaconda-token: ${{ secrets.PREFIXDEV_APIKEY }}