name: sofa-beamadapter
on:
  - workflow_call
  - workflow_dispatch

jobs:
  build-publish-sofa-beamadapter:
    strategy:
      fail-fast: false
      matrix:
        # target: [{platform: "linux-64", runner: "ubuntu-latest"},
        #          {platform: "linux-aarch64", runner: "ubuntu-22.04-arm"},
        #          {platform: "osx-64", runner: "macos-13"},
        #          {platform: "osx-arm64", runner: "macos-14"},
        #          {platform: "win-64", runner: "windows-latest"}]
        target: [{platform: "linux-aarch64", runner: "ubuntu-22.04-arm"}]

    uses: ./.github/workflows/build_publish_package.yml
    with:
      package-name: sofa-beamadapter
      runner: ${{ matrix.target.runner }}
      platform: ${{ matrix.target.platform }}
      anaconda-channel: sofa-framework
      recipe-dir: release-v24.12
    secrets:
      anaconda-token: ${{ secrets.ANACONDA_TOKEN }}